version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:

  postgres:
    image: hagen013/hg_shop_postgres
    restart: unless-stopped
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    env_file:
      - env/postgres

  redis:
    restart: unless-stopped
    hostname: redis
    image: redis:latest

  # RabbitMQ
  rabbit:
    restart: unless-stopped
    image: rabbitmq:3.7.4-management-alpine
    env_file:
      - env/rabbit
    ports:
      - "5672:5672"
      - "15671:15672"

  hg_shop:
    restart: unless-stopped
    image: hagen013/hg_shop_shop
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    env_file:
      - env/django
    depends_on:
      - postgres
      - redis
      - rabbit
    links:
      - rabbit
      - postgres
      - redis

  celery:
    restart: unless-stopped
    image: hagen013/hg_shop_celery
    build:
      context: .
      dockerfile: ./compose/celery/Dockerfile
    env_file:
      - env/django
    depends_on:
      - hg_shop
    links:
      - rabbit
      - postgres
      - redis

  nginx:
    image: hagen013/hg_shop_nginx2
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    depends_on:
      - hg_shop
    ports:
      - "80:80"
    links:
      - hg_shop:hg_shop
    volumes:
      - /var/media:/media
