# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_productphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Новый'), (2, 'В обработке'), (3, 'Завершен'), (4, 'Отменен')], default=1, verbose_name='статус')),
                ('order_text', models.TextField(blank=True, verbose_name='текст заказа')),
                ('name', models.CharField(max_length=512, verbose_name='имя клиента')),
                ('phone', models.CharField(max_length=32, verbose_name='телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='эл. почта')),
                ('adress', models.CharField(blank=True, max_length=512, verbose_name='адрес')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.DefaultOrder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='core.ProductPage')),
            ],
        ),
    ]
