# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultorder',
            name='notified',
            field=models.BooleanField(default=False, verbose_name='уведомлён'),
        ),
    ]
