# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-26 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20170312_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defaultorder',
            name='modified_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Последнее изменение'),
            preserve_default=False,
        ),
    ]
