version: '2'

services:
  rabbit:
    restart: unless-stopped
    image: rabbitmq:3.7.4-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=hg_shop
      - RABBITMQ_DEFAULT_PASS=hg_shop
      - RABBITMQ_DEFAULT_VHOST=api
    ports:
      - "5672:5672"
      - "15671:15672"

  redis:
    restart: unless-stopped
    hostname: redis
    image: redis:latest
    ports:
      - "6379:6379"
