# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 15:35
from __future__ import unicode_literals

import core.db.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_meta_title', models.CharField(blank=True, max_length=256, verbose_name='SEO title')),
                ('_meta_keywords', models.CharField(blank=True, max_length=1024, verbose_name='SEO keywords')),
                ('_meta_description', models.CharField(blank=True, max_length=1024, verbose_name='SEO description')),
                ('slug', core.db.fields.DisplayableSlugField(max_length=1000, unique=True, verbose_name='slug')),
                ('url', core.db.fields.DisplayableURLField(max_length=2000, unique=True, verbose_name='URL')),
                ('scoring', models.IntegerField(default=1000000, verbose_name='Скоринг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='главное изображение')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media/thumb', verbose_name='thumbnail')),
                ('name', core.db.fields.NameField(max_length=500, verbose_name='Наименование')),
                ('description', core.db.fields.DescriptionField(blank=True, default='Без описания', verbose_name='Описание')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='потомок', to='core.CategoryPage', verbose_name='родительская категория')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'category page',
                'verbose_name_plural': 'category pages',
            },
        ),
        migrations.CreateModel(
            name='ProductPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_meta_title', models.CharField(blank=True, max_length=256, verbose_name='SEO title')),
                ('_meta_keywords', models.CharField(blank=True, max_length=1024, verbose_name='SEO keywords')),
                ('_meta_description', models.CharField(blank=True, max_length=1024, verbose_name='SEO description')),
                ('slug', core.db.fields.DisplayableSlugField(max_length=1000, unique=True, verbose_name='slug')),
                ('url', core.db.fields.DisplayableURLField(max_length=2000, unique=True, verbose_name='URL')),
                ('scoring', models.IntegerField(default=1000000, verbose_name='Скоринг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='главное изображение')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media/thumb', verbose_name='thumbnail')),
                ('name', core.db.fields.NameField(max_length=500, verbose_name='Наименование')),
                ('description', core.db.fields.DescriptionField(blank=True, default='Без описания', verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('old_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Старая цена')),
                ('_amount', models.PositiveIntegerField(default=1, verbose_name='количество')),
                ('vendor_code', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='Артикул')),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='аттрибуты')),
                ('is_in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('is_new_product', models.BooleanField(db_index=True, default=False, verbose_name='Новинка')),
                ('is_bestseller', models.BooleanField(db_index=True, default=False, verbose_name='Бестселлер')),
                ('is_searchable', models.BooleanField(default=True, verbose_name='Отображать в поиске')),
                ('_fts_body', models.CharField(blank=True, db_index=True, max_length=512, verbose_name='тело поиска')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.CategoryPage', verbose_name='категория')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'product page',
                'verbose_name_plural': 'product pages',
            },
        ),
    ]
