# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-30 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_productphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypage',
            name='default_scoring',
            field=models.IntegerField(default=0),
        ),
    ]
