# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-30 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categorypage_default_scoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypage',
            name='default_scoring',
            field=models.IntegerField(default=10000, verbose_name='рейтинг товаров в категории'),
        ),
    ]
