# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-12 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180130_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorypage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='categorypage',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='thumbnail',
        ),
    ]
