# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-12 18:08
from __future__ import unicode_literals

import core.db.image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180312_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productphoto',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productphoto',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='productpage',
            name='image',
            field=models.ImageField(blank=True, default='images/0000.png', upload_to=core.db.image.UploadTo, verbose_name='Картинка'),
        ),
    ]
