# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-15 11:29
from __future__ import unicode_literals

import core.db.image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_productphoto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='base_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Базовая цена'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='image',
            field=models.ImageField(blank=True, default='images/0000.jpg', upload_to=core.db.image.UploadTo, verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='image',
            field=models.ImageField(blank=True, default='images/0000.jpg', upload_to=core.db.image.UploadTo, verbose_name='Картинка'),
        ),
    ]
