# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-15 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180315_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='base_price',
            field=models.FloatField(default=0, verbose_name='Базовая цена'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='old_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Старая цена'),
        ),
    ]
