# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-18 12:12
from __future__ import unicode_literals

import core.db.image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180315_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypage',
            name='image',
            field=models.ImageField(blank=True, default='images/0000.jpg', upload_to=core.db.image.UploadTo, verbose_name='Картинка'),
        ),
    ]
