# Generated by Django 2.2.7 on 2019-11-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20181111_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypage',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='categorypage',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='categorypage',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
