# Generated by Django 2.2.7 on 2019-11-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191114_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='productphoto',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
